### ISSUE TITLE
Error on fresh configuration (example fresh saved variables after addon rename)

### ISSUE THREAD

**Issue by Road-block** [cralor/TourGuideVanilla#13]
[NilGuide.lua](https://github.com/cralor/TourGuideVanilla/blob/master/NilGuide.lua) needs this at the top:  
```lua
local L = TourGuide.Locale
```

**Comment by Road-block** [comment]
Also a minor unrelated nitpick 😆  
Non standard tags in .toc need to be prefaced by `X-`, for example `Credits` > `X-Credits` then they can be queried by `GetAddonMetadata(tag)`

**Comment by cralor** [comment]
Awesome. Thanks for the catch, and I was recently thinking about that. Appreciate the input!!
