### ISSUE TITLE
Error running addon 

### ISSUE THREAD

**Issue by cpand671** [cralor/TourGuideVanilla#23]
ERROR:Interface\AddOns\TourGuideVanilla\UnlistedQuest.lua:7: bad argument #1 to 'pairs' (table expected, got nil)

ERROR:Interface\AddOns\TourGuideVanilla\Parser.lua:96: bad argument #1 to 'pairs' (table expected, got string)

I can't run the addon at all

**Comment by cralor** [comment]
Interesting. I will look at this tonight. Thanks for the report.

**Comment by cralor** [comment]
@cpand671 can you share additional information about this error? Have you used the AddOn before? Was this on initial load after installing the AddOn? Were you doing any action to trigger the error?

I just download the latest build off of GitHub here, and have no errors after loading and logging in. There was a couple of small changes that weren't included in the most recent release. Can you try the latest version? Thank you.

**Comment by cpand671** [comment]
Sure, I can try it out tomorrow.

On initial loading of the addon with no data saved into the saved variables folders it gave the parser .lua error.

Upon accepting the first quest it gave the unused quest lua error

**Comment by cpand671** [comment]
I found the issue. For some reason Modified Power Auras by Shino causes Tour Guide to run into issues.

https://github.com/Geigerkind/ModifiedPowerAuras

**Comment by cralor** [comment]
Nice find. I'll load that up on my PC and see what I can gather from it.

**Comment by cralor** [comment]
I couldn't quite discover the true issue, but give the latest changes a try. I think that may fix your issues.
