### ISSUE TITLE
libs and .toc problem

### ISSUE THREAD

**Issue by Road-block** [cralor/TourGuideVanilla#25]
- externals are not automatically pulled into the source package so players getting the addon from master will be missing the `libs` files.
- additionally the .toc should reference `libs\Sol\libs\LibStub\LibStub.lua` before `libs\Sol\Sol.lua` as the former is responsible for loading the LibStub dependency. Without that change the addon will only work for players that have *other* addons loading LibStub.

Hope it helps.

**Comment by Road-block** [comment]
Just to add here that the *obvious* solution to the .toc issue of instead referencing `libs\Sol\Sol.xml` which loads both LibStub.lua and Sol.lua will not work when the Sol library is embedded and not loaded as a standalone addon.

**Comment by Road-block** [comment]
Not to open a separate ticket but after fixing the library and .toc issues I'm also getting this load time errors.
```
Interface\AddOns\TourGuideVanilla\Parser.lua:96: bad argument #1 to `pairs' (table expected, got string)
Interface\AddOns\TourGuideVanilla\StatusFrame.lua:144: bad argument #1 to `ipairs' (table expected, got nil)
Interface\AddOns\TourGuideVanilla\TourGuide.lua:179: attempt to index field `actions' (a nil value)
Interface\AddOns\TourGuideVanilla\TourGuide.lua:179: attempt to index field `actions' (a nil value)
Interface\AddOns\TourGuideVanilla\TourGuide.lua:179: attempt to index field `actions' (a nil value)
Interface\AddOns\TourGuideVanilla\TourGuide.lua:179: attempt to index field `actions' (a nil value)
Interface\AddOns\TourGuideVanilla\TourGuide.lua:179: attempt to index field `actions' (a nil value)
```
With previous saved variables or after clearing them.  
alpha problems I know 😋

**Comment by cralor** [comment]
Thanks Road-block. I just grabbed the versions of the libraries I want and put them in manually, removing the submodules and correct these errors.
