### ISSUE TITLE
Classic Beta Version

### ISSUE THREAD

**Issue by christophrus** [cralor/TourGuideVanilla#39]
Can you make a version that works with the classic beta? :)

**Comment by cralor** [comment]
Sometime in the future, yes!

**Comment by padmanek** [comment]
Problem is, you'd have to almost rewrite it form scratch. Classic (Beta) is using modern, stripped BFA client. LUA version is much more evolved. If you try to put a 1.12 add-on in the Classic Beta, you will have bad syntax explosions all over the place.

**Comment by cralor** [comment]
Yep. Just merge this project with TourGuide last build in Cataclysm and go
from there.

**Comment by cralor** [comment]
Starting out here: https://github.com/cralor/TourGuideClassic
