### ISSUE TITLE
Permission to reuse your guides for a Classic addon

### ISSUE THREAD

**Issue by max-ri** [cralor/TourGuideVanilla#42]
Hi, 
I am working on a similar addon for Classic and I was wondering whether it would be ok for you if I was reusing the guides from your addon for it (while crediting you of course).

Another question: I read that your guides are (in part?) based off of Joana's. Is this right? I know that he doesn't like his guides being used in addons. Have you ever been in contact with him about it?

**Comment by cralor** [comment]
Sorry for missing this. It looks like you've got Guidelime up and running. Nice project.

I'm going to start slowly working on updating this for Classic. I'll need to revise my included guides with it, but feel free to use anything here.

You're allowed to use anyone's existing guides as a base guideline. e.g. the steps they use aren't copyright. However, their work, including their wording and text, is.
