### ISSUE TITLE
new race

### ISSUE THREAD

**Issue by Meridaw** [cralor/TourGuideVanilla#5]
I downloaded the new update, but this time playing on a human paladin, Tourguide started at the point i left on my dwarf priest. I went into the menu and selected the human starting zone, but the addon starts from first quest, when my paladin was lvl 5, so i had to skip past all the quests that i already did before.

**Comment by cralor** [comment]
Hmm... each character should have its own progress. So that is a bit odd.

However, you will have to manually "skip" actions that TourGuide hasn't "seen" itself if installing/using it for the first time not at the beginning of a zone's steps.

**Comment by Meridaw** [comment]
Yeah i thought that was the case, but wanted to say it anyway, just in case you can do some light detection. I was thinking, if you log into goldshire you could get the starting quest from goldshire, or if your in westfall you get those, and maybe skip quest`s that are way to low level for you.

**Comment by Meridaw** [comment]
![dead](https://user-images.githubusercontent.com/26133646/38170129-f7163fb2-357c-11e8-84e2-e59faf7b5b6c.png)
My corpse is way closer then this in another direction.

**Comment by cralor** [comment]
Re: light detection... yeah, I like the idea. I don't know what the vanilla API is like for quest data. I know it is probably nothing compared to what they added in TBC/WOTLK (or whatever xpac that was).

Re: dead corpse arrow... that logic is entirely within TomTom. I haven't really messed with it too much, but given the wording of "My possibly dead corpse", I figured situations like yours were why it wasn't always correct. I haven't had any issue with it thus far, but can imagine your situation being a potential issue.

I can add a check when you logout (and are dead) to "save" the location and present that on login.

**Comment by Meridaw** [comment]
Great. I noticed you get additional info in the tooltip if you mouseover the Tourguide,  Maybe it would be better to have this info in the same frame as the Tourguide steps? it`s pretty easy to mess things up in town/quest hub, when you deliver the quests.

**Comment by cralor** [comment]
What do you mean by "mess things up"?

The intent is to be small and unobtrusive. When you talk to an NPC to accept a quest, TourGuide will tell you at the top of the quest pane whether or not it is a part of your guide (if it says nothing, it is a part of the guide). You don't have to focus too much on following the steps to the exact "T". Does that make sense?

**Comment by Meridaw** [comment]
ah, i got this addon that auto accept quests, so i missed the thing a top of the quest pane. It just made it look like the addon was skipping steps, if i did not do it in the correct order.

**Comment by Meridaw** [comment]
So i got to westfall, and the step says Furlbrow's Deed. I did not see this quest, so i googled. It is a low drop of the Defias mobs, maybe not the best first step in westfall?

**Comment by Meridaw** [comment]
![ghost](https://user-images.githubusercontent.com/26133646/38452295-7ac213a4-3a41-11e8-99a7-0ddf9a4b570e.png)

**Comment by cralor** [comment]
Re; Elwynn Forest quests... yes, they may need a big of cleaning up here and there. Eventually.

Thanks for catching that, I thought I removed it at one point, but I went ahead and removed it again :)
I also went ahead and re-did the first handful of zones on the Horde side. If you were leveling within these zones, you'll have to do a quick check on the actions you've already completed, unfortunately, but the guide should now be more efficient and be more tailored to the vanilla WoW again. Cheers.

**Comment by Meridaw** [comment]
Nice, also i dont see Tirisfall Glades 1-12 on the guide list.

**Comment by Meridaw** [comment]
![not listed](https://user-images.githubusercontent.com/26133646/38464393-76ee6788-3b0d-11e8-922c-a967b1524178.png)

**Comment by Meridaw** [comment]
Looks like there is more then one quest with the same name and issue.
![not list part 2](https://user-images.githubusercontent.com/26133646/38464834-539b46f0-3b14-11e8-83d5-2e3a9cc20606.png)
