### ISSUE TITLE
Clarification Request: Purpose of *.toc files in TourGuide_Alliance and TourGuide_Horde folders

### ISSUE THREAD

**Issue by refaim** [cralor/TourGuideVanilla#51]
Hello there!

I'm currently working on an addon manager for Vanilla WoW, and while exploring your addon, I came across an issue that I'd like to discuss. I noticed the following concern regarding your addon: https://github.com/refaim/snapjaw/issues/22.

I kindly request your assistance in providing some clarification regarding the purpose of the *.toc files present in the `TourGuide_Alliance` and `TourGuide_Horde` folders. Based on my observation, it appears that both the Horde and Alliance `Guides.xml` files are loaded from the `TourGuideVanilla.toc` file in the root folder.

Thank you for your time and attention. I look forward to your response.

**Comment by Road-block** [comment]
The intention was probably to have the 2 folders dragged out into the AddOns folder and let the player only load the one for their faction.

I would just ignore .toc files in subfolders of addons. There will be more cases like this for other addons, or source folders that are intended to work along-side a packaging script that moves plugin addons, out.

**Comment by cralor** [comment]
Road block is correct. While in this case the TOC files in the subfolders can be removed, as they are provided with the AddOn, the purpose is to show that anyone can use the TourGuide framework with their own AddOn (plugin) separately.

**Comment by refaim** [comment]
Thank you all for your responses.
