### ISSUE TITLE
Parts of the guide not showing in the list.

### ISSUE THREAD

**Issue by Random1338** [cralor/TourGuideVanilla#7]
For some reason the undead, dwarf and professions guides don't show in the list for me... the guides however are there on an undead it did load and work for that area but its not in the guide selection any insight on what might be causing this would be great.

![slight problem](https://user-images.githubusercontent.com/38775727/39344217-17cf0072-49af-11e8-9216-ec8579056e15.png)

**Comment by cralor** [comment]
Thanks for the report. I've noticed this once before, I will have to dig into it further.

**Comment by cralor** [comment]
Still debugging... appears, at least for the profession guides, that on initial login they are not being recognized w/ correct Faction information. I've attempted a fix, but it isn't working accordingly yet.

In the mean time, reloading the UI after initial login should correct the issue.

**Comment by cralor** [comment]
Also, I'm now realizing GuideList and GuideListFrame are one in the same, so I will be removing GuideList (unused) in the next update.

**Comment by Road-block** [comment]
That sounds like a loading order issue (when something happens / doesn't happen on a "cold" login (from fully exited or going back to character selection) vs a /console reloadui that's a clear indication. The order of startup events is not exactly the same between the two scenarios.  
The solution is to use an event that's further down the chain (for example PLAYER_LOGIN or PLAYER_ENTERING_WORLD) for the affected initialization or a workaround that doesn't rely on the same methods.  
For example a typical *trick* for detecting faction without relying on the `UnitFactionGroup("player")` API is to check the return of `UnitRace("player")` against a static list instead, as the second returns proper values before login.

**Comment by Random1338** [comment]
Haven't checked this in a bit. reloadui does indeed fix it for now :). Thank you for looking into it and the addon :)

**Comment by cralor** [comment]
Weird issues with `unpack`. Latest commit fixes this issue! I'll mark a release shortly.
