### ISSUE TITLE
Guide's switching.

### ISSUE THREAD

**Issue by Hiffix** [cralor/TourGuideVanilla#9]
TourGuide\TourGuide.lua:132: attempt to call method `UpdateGuidesPanel' (a nil value)
TourGuide\Dongle.lua:338: in function <Interface\AddOns\TourGuide\Dongle.lua:332>
TourGuide\Dongle.lua:1250: in function <Interface\AddOns\TourGuide\Dongle.lua:1250>
TourGuide\TourGuide.lua:199: table index is nil
TourGuide\TourGuide.lua:199: in function `SetTurnedIn'
TourGuide\StatusFrame.lua:289: in function <Interface\AddOns\TourGuide\StatusFrame.lua:289>
TourGuide\TourGuide.lua:132: attempt to call method UpdateGuidesPanel' (a nil value)
TourGuide\TourGuide.lua:132: in functionLoadNextGuide'

this is error from ending 1st guide and switching for next one
horde Trisfal Glades > The Barrens

**Comment by cralor** [comment]
This is a result of removing one of the old files and not renaming this function. Fixed for the next update! Thanks!

**Comment by Road-block** [comment]
Just a note for people (like me) that want to fix this before next push, replacing the erroring line with `UpdateGuideListPanel()` should work.

**Comment by cralor** [comment]
Thanks road block :) Made a commit for now.
